In [2]:
import numpy as np
from scipy import linalg as la

In [3]:
matrix = np.array(
    [[1, 0, 0, -1j], [0, 1, 1j, 0], [0, 1j, 1, 0], [-1j, 0, 0, 1]]
) / np.sqrt(2)

la.det(matrix)

np.complex128(0.9999999999999997+0j)

In [ ]:
matrix @ matrix.T

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [103]:
from tai_localizer.perulizer.misc import sigma_x, sigma_y, sigma_z

v = np.kron(sigma_y, sigma_y)

e, vec = la.eigh(v)
e = 1j * e
vec @ np.diag(e) @ vec.conj().T

array([[0.+2.44415748e-16j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.-1.00000000e+00j],
       [0.+0.00000000e+00j, 0.+8.35989996e-16j, 0.+1.00000000e+00j,
        0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+1.00000000e+00j, 0.+2.44415748e-16j,
        0.+0.00000000e+00j],
       [0.-1.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+8.35989996e-16j]])

In [104]:
2 * np.round(vec @ np.diag(np.sqrt(e)) @ vec.T / np.sqrt(2), 8)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 1.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 1.+0.j, 0.+0.j],
       [0.-1.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [ ]:
from scipy.stats import unitary_group

x = unitary_group.rvs(4)

In [108]:
u = x @ v @ x.T  # this is defo unitary but not special unitary

np.round(vec @ vec.T, 4).real

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.],
       [ 0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])